# DATA DIRECTORIES
p_drive_location:
  /pdrive/projects/ene.model3
  #P:/ene.model

# SCENARIO INFORMATION
scenario:
  start_model: # in model_scenarios
  start_scen:
  target_model:
  target_scen:
  first_model_year:
    2030
  regions:
    R12

models_scenarios:
#  SSP1:
#    model: SSP_SSP1_v6.2
#    scenario: baseline
  SSP2:
    model: SSP_SSP2_v6.2
    scenario: baseline
#  SSP3:
#    model: SSP_SSP3_v6.2
#    scenario: baseline
#  SSP4:
#    model: SSP_SSP4_v6.2
#    scenario: baseline
#  SSP5:
#    model: SSP_SSP5_v6.2
#    scenario: baseline

# COVERED TRADE TECHNOLOGIES
covered_trade_technologies:
  - gas_piped
  - LNG_shipped
  - coal_shipped
  - crudeoil_shipped
  - crudeoil_piped
  - eth_shipped
  - foil_shipped
  - foil_piped
  - loil_shipped
  - loil_piped
  - biomass_shipped
  - lh2_shipped

# SHIPPING FUELS (how much of each shipping technology is propelled by each fuel)
shipping_fuels:
  LNG_tanker:
    LNG_tanker_LNG: 0.8
    LNG_tanker_loil: 0.2
  oil_tanker:
    oil_tanker_loil: 0.9
    oil_tanker_foil: 0.07
    oil_tanker_eth: 0.03

# YEARS
timeframes:
  year_act_list:
    - 2010
    - 2015
    - 2020
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050
    - 2055
    - 2060
    - 2070
    - 2080
    - 2090
    - 2100
    - 2110
  year_vtg_list:
    - 2010
    - 2015
    - 2020
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050
    - 2055
    - 2060
    - 2070
    - 2080
    - 2090
    - 2100
    - 2110

# PARAMETERS THAT NEED TO BE DEFINED
define_parameters:
  base_required_par: # Parameters that need to be defined at a minimum
      - input
      - output
      - technical_lifetime
      - inv_cost
      - fix_cost
      - var_cost
      - capacity_factor

# CONSTRAINT PARAMETERS
constraint_values:
  gas_piped:
    growth_activity_lo: -0.1
    growth_activity_up: 0.1
  LNG_shipped:
    growth_activity_lo: -0.1
    growth_activity_up: 0.1    

# SENSITIVITY SCENARIOS
sensitivities:
  FSU_frictions:
    R12_FSU:
      - gas_piped_exp_weu
      - gas_piped_exp_nam
      - LNG_shipped_exp_weu
      - LNG_shipped_exp_nam
      - coal_shipped_exp_weu
      - coal_shipped_exp_nam
      - crudeoil_shipped_exp_weu
      - crudeoil_shipped_exp_nam
      - crudeoil_piped_exp_weu
      - crudeoil_piped_exp_nam
      - eth_shipped_exp_weu
      - eth_shipped_exp_nam
      - foil_shipped_exp_weu
      - foil_shipped_exp_nam
      - foil_piped_exp_weu
      - foil_piped_exp_nam   
      - loil_shipped_exp_weu
      - loil_shipped_exp_nam
      - loil_piped_exp_weu
      - loil_piped_exp_nam       
      - biomass_shipped_exp_weu
      - biomass_shipped_exp_nam
      - lh2_shipped_exp_weu
      - lh2_shipped_exp_nam    
  FSU_WEU_frictions:
    R12_FSU:
      - gas_piped_exp_weu
      - LNG_shipped_exp_weu
      - coal_shipped_exp_weu
      - crudeoil_shipped_exp_weu
      - crudeoil_piped_exp_weu
      - eth_shipped_exp_weu
      - foil_shipped_exp_weu
      - foil_piped_exp_weu
      - loil_shipped_exp_weu
      - loil_piped_exp_weu
      - biomass_shipped_exp_weu
      - lh2_shipped_exp_weu
