# HHI constraint on gas imports and production in R12_WEU
weu_gas_supply:
  nodes:
    - R12_WEU
  value:
    0.8
  technologies:
    - gas_piped_exp_weu
    - LNG_shipped_exp_weu
    - coal_gas
    - gas_bal
    - gas_bio
    - h2_mix
      